var a = 10;
var b = 5;
var totalSoma = a + b;
var totalSubtr = a - b;
var totalMult = a * b;
var totalDiv = a / b;
var totalResto = a % b;
console.log("Soma: ".concat(totalSoma, " + Subtra\u00E7\u00E3o: ").concat(totalSubtr, " + Multiplica\u00E7\u00E3o: ").concat(totalMult, " + Divis\u00E3o: ").concat(totalDiv, " + Resto: ").concat(totalResto));
var nome = "Lucas";
var sobrenome = "Silva";
var textoConcatenado = nome + sobrenome;
console.log("Nome completo: ".concat(textoConcatenado));
var textoRepetido = nome.repeat(3);
console.log("Nome repetido: ".concat(textoRepetido));
